### ISSUE TITLE
Parsing JaSPer post gulps on missing contest city

### ISSUE THREAD

**Issue by wbreeze** [wbreeze/iaccdb#63]
:: undefined method `strip' for nil:NilClass ::
/data/home/webmaster/iaccdb/releases/20180427210620/app/services/jasper/jasper_to_db.rb:41:in `extract_contest_params_hash'
/data/home/webmaster/iaccdb/releases/20180427210620/app/services/jasper/jasper_to_db.rb:21:in `process_contest'

Make this more robust. Do we need contest city? Is it required? The trouble when we fail to parse JaSPer posts is that JaSPer successfully posted. The parsing is after the fact, a background task. JaSPer can't know about the parsing errors, or any other errors for that matter. Can we do better?

**Comment by wbreeze** [comment]
Only we're not using Nokogiri. We're using LibXML. [`inner_xml`](http://xml4r.github.io/libxml-ruby/rdoc/classes/LibXML/XML/Node.html#method-i-inner_xml)

**Comment by wbreeze** [comment]
closed by PR #64
